# basic options
title: Special-Force-Analytic
author: Sarunkorn C. and Witchapong D.
email: email@gmail.com
description: A data analytic for e-commerce showcase site

header_pages:
- about.md
- appendix.md

# Build settings
markdown: kramdown
theme: minima
