# basic options
title: Special-Force-Analytic
author: Mik and Mo
email: wdaroontham@gmail.com and sarunkorn.cho@gmail.com
description: A wonderful data analytic site

# Build settings
markdown: kramdown
theme: minima
