# basic options
title: DigitAIs
description: A data-driven and analytics platform consulting company
author: Sarunkorn C. and Witchapong D.
email: sarunkorn.cho@gmail.com <br> wdaroontham@gmail.com

header_pages:
- about.md
- service.md
- usecase.md

plugins:
  - jekyll-titles-from-headings
  - jekyll-image-size

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false

# Build settings
markdown: kramdown
theme: minima
