# basic options
title: Special-Force-Analytic
author: Mo & Mick
email: your-email@domain.com
description: A wonderful data analytic site

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
