# basic options
title: Special-Force-Analytic
author: Witchapong D. and Sarunkorn C.
email: email@gmail.com
description: A data analytic for e-commerce showcase site

# Build settings
markdown: kramdown
theme: minima
