# basic options
title: Special-Force-Analytic
description: A data analytic for e-commerce showcase site
author: Sarunkorn C. and Witchapong D.
email: email@gmail.com

header_pages:
- about.md
- analyses.md

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: false

# Build settings
markdown: kramdown
theme: minima
